OMDB_ENDPOINT = 'http://www.omdbapi.com/'
OMDB_API_KEY = 'ff997d27'

OWM_ENDPOINT = 'https://api.openweathermap.org/data/2.5/forecast'
OWM_API_KEY = '5c0be521628ced88241158b7b7122011'

GMAIL_USERNAME = 'anuj.nits2@gmail.com'
GMAIL_PASSWORD = 'wzgpcyhchhcdoret'
SMTP_HOST = 'smtp.gmail.com'
SMTP_PORT = 587

OPEN_TRIVIA_ENDPOINT = 'https://opentdb.com/api.php'
OPEN_TRIVIA_USERNAME = 'anuj'
OPEN_TRIVIA_PASSWORD = 'anuj.nits2'

KITSU_API_ENDPOINT = 'https://kitsu.io/api/edge/anime'
