OMDB_ENDPOINT = 'http://www.omdbapi.com/'
OMDB_API_KEY = 'ff997d27'
OPEN_TRIVIA_ENDPOINT = 'https://opentdb.com/api.php'
KITSU_API_ENDPOINT = 'https://kitsu.io/api/edge/anime'
THE_MEAL_DB_API_ENDPOINT = 'https://www.themealdb.com/api/json/v1/1/search.php?s='
